<?php
return [
    'menu' => [
        'countdown' => [
            'position' => 7,
            'name' => 'countdown',
            'title' => 'Hitung Mundur',
            'description' => 'Menu Untuk Mengelola Pengumuman',
            'parent' => false,
            'icon' => 'fa-hourglass',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Hitung Mundur',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => true,
                'editor' => false,
                'category' => false,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => array(
                    ['Tanggal', 'date', 'required'],
                )
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => false,
                'detail' => false,
                'history' => false,
                'auto_query' => false,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => true,
            'active' => true,
        ],
        'pengumuman' => [
            'position' => 3,
            'name' => 'pengumuman',
            'title' => 'Pengumuman',
            'description' => 'Menu Untuk Mengelola Pengumuman',
            'parent' => false,
            'icon' => 'fa-info',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Judul Pengumuman',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => false,
                'editor' => true,
                'category' => false,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => array(
                    ['Lampiran', 'file']
                )
            ],
            'web' => [
                'api' => true,
                'archive' => true,
                'index' => true,
                'detail' => true,
                'history' => true,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'galeri' => [
            'position' => 5,
            'name' => 'galeri',
            'title' => 'Galeri',
            'description' => 'Menu untuk mengelola galeri',
            'parent' => false,
            'icon' => 'fa-camera',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Galeri',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => true,
                'editor' => true,
                'category' => true,
                'tag' => true,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => array(['Link Video', 'text']),
            ],
            'web' => [
                'api' => true,
                'archive' => true,
                'index' => true,
                'detail' => true,
                'history' => true,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'sambutan' => [
            'position' => 6,
            'name' => 'sambutan',
            'title' => 'Sambutan',
            'description' => 'Menu Untuk Mengelola Sambutan',
            'parent' => false,
            'icon' => 'fa-quote-left',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Sambutan',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => true,
                'editor' => true,
                'category' => false,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => [
                    ['Pemberi Sambutan', 'break'],
                    ['Nama', 'text', 'required'],
                    ['Jabatan', 'text', 'required'],
                    ['Visi Misi', 'textarea'],

                ],
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => false,
                'detail' => false,
                'history' => false,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'kepegawaian' => [
            'position' => 4,
            'name' => 'kepegawaian',
            'title' => 'Kepegawaian',
            'description' => 'Menu Untuk Mengelola Kepegawaian',
            'parent' => false,
            'icon' => 'fa-id-card',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => 'Jabatan',
                'data_title' => 'Nama Pegawai',
            ],
            'form' => [
                'unique_title' => true,
                'post_parent' => ['Unit Kerja', 'unit-kerja'],
                'thumbnail' => true,
                'editor' => false,
                'category' => true,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => [
                    ['NIP', 'text', 'required'],
                    ['Kelahiran', 'text', 'required'],
                    ['Jabatan', 'text', 'required'],
                    ['Pangkat/Golongan', 'text', 'required'],
                    ['Pendidikan', 'text', 'required'],
                    ['Tahun Mulai', 'text', 'required'],
                    ['Motivasi', 'textarea'],
                ],
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => true,
                'detail' => false,
                'history' => false,
                'auto_query' => true,
                'sortable' => true,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'unit-kerja' => [
            'position' => 7,
            'name' => 'unit-kerja',
            'title' => 'Unit Kerja',
            'description' => 'Menu Untuk Mengelola Unit Kerja',
            'parent' => false,
            'icon' => 'fa-sitemap',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => 'Website',
                'data_title' => 'Nama Unit',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => ['Unit Induk','unit-kerja'],
                'thumbnail' => true,
                'editor' => true,
                'category' => true,
                'tag' => true,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => [
                    ['Pemerintahan','break'],
                    ['Kepala','text'],
                    ['Sekretaris','text'],
                    ['Kantor','break'],
                    ['Alamat','text'],
                    ['Email','text'],
                    ['Telp','text'],
                    ['Link SIPPN','text'],
                    ['Google Maps','text'],
                    ['Instagram','text'],
                    ['Facebook','text'],
                    ['Website','text'],
                ],
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => true,
                'detail' => true,
                'history' => false,
                'auto_query' => true,
                'sortable' => true,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'page' => [
            'position' => 1,
            'name' => 'page',
            'title' => 'Halaman',
            'description' => 'Menu Untuk Mengelola Halaman',
            'parent' => false,
            'icon' => 'fa-file-code',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Halaman',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => true,
                'editor' => true,
                'category' => false,
                'tag' => true,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => array(
                    ['Tanggal Entry', 'datetime']
                ),
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => false,
                'detail' => true,
                'history' => false,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'berita' => [
            'position' => 1,
            'name' => 'berita',
            'title' => 'Berita',
            'description' => 'Menu Untuk Mengelola Berita',
            'parent' => false,
            'icon' => 'fa-newspaper-o',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Judul Berita',
            ],
            'form' => [
                'unique_title' => true,
                'post_parent' => false,
                'thumbnail' => true,
                'editor' => true,
                'category' => true,
                'tag' => true,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => array(
                    ['Tanggal Entry', 'datetime']
                ),
            ],
            'web' => [
                'api' => true,
                'archive' => true,
                'index' => true,
                'detail' => true,
                'history' => true,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'download' => [
            'position' => 3,
            'name' => 'download',
            'title' => 'Dokumen',
            'description' => 'Menu Untuk Mengelola Dokumen',
            'parent' => false,
            'icon' => 'fa-download',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Dokumen',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => false,
                'editor' => false,
                'category' => true,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => array(
                    ['File', 'file', 'required'],
                    ['Tanggal Entry', 'datetime']
                ),
            ],
            'web' => [
                'api' => true,
                'archive' => true,
                'index' => true,
                'detail' => true,
                'history' => true,
                'auto_query' => false,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
           'document' => [
            'position' => 3,
            'name' => 'document',
            'title' => 'Dokumen',
            'description' => 'Menu Untuk Mengelola Dokumen',
            'parent' => false,
            'icon' => 'fa-download',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Dokumen',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => false,
                'editor' => false,
                'category' => true,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => array(
                    ['File', 'file', 'required'],
                    ['Tanggal Entry', 'datetime']
                ),
            ],
            'web' => [
                'api' => true,
                'archive' => true,
                'index' => true,
                'detail' => true,
                'history' => true,
                'auto_query' => false,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'layanan' => [
            'position' => 4,
            'name' => 'layanan',
            'title' => 'Layanan',
            'description' => 'Menu Untuk Mengelola Layanan',
            'parent' => false,
            'icon' => 'fa-desktop',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Layanan',
            ],
            'form' => [
                'unique_title' => true,
                'post_parent' => false,
                'thumbnail' => true,
                'editor' => true,
                'category' => false,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => false,
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => true,
                'detail' => true,
                'history' => false,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'sakip' => [
            'position' => 4,
            'name' => 'sakip',
            'title' => 'Dokumen Sakip',
            'description' => 'Menu Untuk Mengelola Dokumen Sakip',
            'parent' => false,
            'icon' => 'fa-file-pdf',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Dokumen',
            ],
            'form' => [
                'unique_title' => true,
                'post_parent' => ['Perangkat Daerah', 'unit-kerja'],
                'thumbnail' => true,
                'editor' => false,
                'category' => true,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => [
                    ['File', 'file','required'],
                    ['Tahun', 'number'],
                    ['Tanggal Entry', 'datetime-local'],
                 
                ],
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => true,
                'detail' => true,
                'history' => false,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'kelurahan-desa' => [
            'position' => 4,
            'name' => 'kelurahan-desa',
            'title' => 'Kelurahan & Desa',
            'description' => 'Menu Untuk Mengelola Kelurahan & Desa',
            'parent' => false,
            'icon' => 'fa-building-wheat',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => 'Website',
                'data_title' => 'Nama Kelurahan Desa',
            ],
            'form' => [
                'unique_title' => true,
                'post_parent' => ['Kecamatan', 'unit-kerja', 'kecamatan'],
                'thumbnail' => true,
                'editor' => true,
                'category' => true,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => [
                    ['Alamat Kantor', 'text'],
                    ['Email', 'email'],
                    ['Telp', 'text'],
                    ['Website', 'text'],
                ],
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => true,
                'detail' => true,
                'history' => false,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'skpd' => [
            'position' => 4,
            'name' => 'skpd',
            'title' => 'Perangkat Daerah',
            'description' => 'Menu Untuk Mengelola Satuan Kerja Perangkat Daerah',
            'parent' => false,
            'icon' => 'fa-building-wheat',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Perangkat Daerah',
            ],
            'form' => [
                'unique_title' => true,
                'post_parent' => false,
                'thumbnail' => true,
                'editor' => true,
                'category' => true,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => [
                    ['Alamat Kantor', 'text'],
                    ['Email', 'email'],
                    ['Telp', 'text'],
                    ['Website', 'text'],
                ],
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => true,
                'detail' => true,
                'history' => false,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'directory' => [
            'position' => 4,
            'name' => 'directory',
            'title' => 'Direktori',
            'description' => 'Menu Untuk Mengelola Direktori',
            'parent' => false,
            'icon' => 'fa-folder',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Direktori',
            ],
            'form' => [
                'unique_title' => true,
                'post_parent' => ['Lokasi','kelurahan-desa'],
                'thumbnail' => true,
                'editor' => true,
                'category' => true,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => [
                    ['Alamat', 'text'],
                    ['Telp', 'text'],
                    ['Instagram', 'text'],
                    ['Facebook', 'text'],
                    ['Youtube', 'text'],
                    ['Website', 'text'],
                ],
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => true,
                'detail' => true,
                'history' => false,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'faq' => [
            'position' => 4,
            'name' => 'faq',
            'title' => 'FAQ',
            'description' => 'Menu Untuk Mengelola FAQ',
            'parent' => false,
            'icon' => 'fa-question',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Pertanyaan',
            ],
            'form' => [
                'unique_title' => true,
                'post_parent' => false,
                'thumbnail' => false,
                'editor' => true,
                'category' => false,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => false
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => true,
                'detail' => true,
                'history' => false,
                'auto_query' => true,
                'sortable' => true,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'sites' => [
            'position' => 15,
            'name' => 'sites',
            'title' => 'Situs',
            'description' => 'Menu Untuk Mengelola Situs',
            'parent' => false,
            'icon' => 'fa-globe',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => 'Nama',
                'data_title' => 'Domain',
            ],
            'form' => [
                'unique_title' => true,
                'post_parent' => false,
                'thumbnail' => true,
                'editor' => false,
                'category' => false,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => [
                    ['Info', 'break'],
                    ['Nama', 'text', 'required'],
                    ['Deskripsi', 'text'],
                    ['Status', ['Aktif','Tidak Aktif']],
                    ['Status Maintenance', ['Aktif', 'Tidak Aktif']],
                    ['Hosting', 'break'],
                    ['Provider', 'text'],
                    ['IP', 'text'],
                    ['NS', 'text'],
                    ['Aktif Tanggal', 'date'],
                    ['Nonaktif Tanggal', 'date'],
                    ['Pengelola', 'break'],
                    ['Nama Pengelola', 'text'],
                    ['Whatsapp', 'text'],
                    ['Email', 'text'],
                    ['Login', 'break'],
                    ['API Key', 'text'],
                    ['URL Login', 'text'],  
                    ['Username', 'text'],
                    ['Password', 'text'],
                ],
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => false,
                'detail' => false,
                'history' => false,
                'auto_query' => false,
                'sortable' => false,
            ],
            'public' => false,
            'cache' => false,
            'active' => true,
        ],
        'link-terkait' => [
            'position' => 10,
            'name' => 'link-terkait',
            'title' => 'Link Terkait',
            'description' => 'Menu Untuk Mengelola Link Terkait',
            'parent' => false,
            'icon' => 'fa-link',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Link',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => true,
                'editor' => false,
                'category' => false,
                'tag' => false,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => false,
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => true,
                'detail' => true,
                'history' => false,
                'auto_query' => false,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'agenda' => [
            'position' => 2,
            'name' => 'agenda',
            'title' => 'Agenda',
            'description' => 'Menu Untuk Mengelola Agenda',
            'parent' => false,
            'icon' => 'fa-calendar-o',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Tema',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => false,
                'editor' => true,
                'category' => true,
                'tag' => true,
                'looping_name' => 'Arsip',
                'looping_data' => false,
                'custom_field' => array(
                    ['Jam', 'datetime'],
                    ['Tempat', 'text'],
                    ['Alamat', 'text'],
                    ['Pejabat', 'text'],
                    ['Tanggal Entry', 'datetime']
                ),
            ],
            'web' => [
                'api' => true,
                'archive' => true,
                'index' => true,
                'detail' => true,
                'history' => true,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'statistik' => [
            'position' => 2,
            'name' => 'statistik',
            'title' => 'Data Statistik',
            'description' => 'Menu Untuk Mengelola Statistik',
            'parent' => false,
            'icon' => 'fa-bar-chart',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Statistik',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => false,
                'editor' => false,
                'category' => false,
                'tag' => true,
                'looping_name' => 'Periode',
                'looping_data' => array(
                    ['Tahun', range(2000, 2025)],
                    ['Data Excel', 'file']
                ),
                'custom_field' => false
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => true,
                'detail' => true,
                'history' => false,
                'auto_query' => true,
                'sortable' => false,
            ],
            'public' => true,
            'cache' => false,
            'active' => true,
        ],
        'menu' => [
            'position' => 11,
            'name' => 'menu',
            'title' => 'Menu',
            'description' => 'Menu Untuk Mengelola Agenda',
            'parent' => false,
            'icon' => 'fa-list-ul',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Menu',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => false,
                'editor' => false,
                'category' => false,
                'tag' => false,
                'looping_name' => 'Daftar Menu',
                'looping_data' => array(
                    ['menu_id', 'text'],
                    ['menu_parent', 'text'],
                    ['menu_name', 'text'],
                    ['menu_description', 'text'],
                    ['menu_link', 'text'],
                    ['menu_icon', 'text']
                ),
                'custom_field' => false,
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => false,
                'detail' => false,
                'history' => false,
                'auto_query' => false,
                'sortable' => false,
            ],
            'public' => false,
            'cache' => false,
            'active' => true,
        ],

        'banner' => [
            'position' => 11,
            'name' => 'banner',
            'title' => 'Banner',
            'description' => 'Menu Untuk Melihat Banner',
            'parent' => false,
            'icon' => 'fa-image',
            'route' => ['index', 'create', 'show', 'update', 'delete'],
            'datatable' => [
                'custom_column' => false,
                'data_title' => 'Nama Banner',
            ],
            'form' => [
                'unique_title' => false,
                'post_parent' => false,
                'thumbnail' => true,
                'editor' => false,
                'category' => true,
                'tag' => false,
                'looping_name' => 'Daftar Menu',
                'looping_data' => false,
                'custom_field' => [['Description', 'textarea']],
            ],
            'web' => [
                'api' => false,
                'archive' => false,
                'index' => false,
                'detail' => false,
                'history' => false,
                'auto_query' => false,
                'sortable' => false,
            ],
            'public' => false,
            'cache' => false,
            'active' => true,
        ]
    ],
    'config' => [
        'web_type' => null,
        'option' => array(),
        'template_asset' => array(),
        'template_info' => array(),
    ],
    'option' => array(),
    'used' => array(),
    'current' => null,
    'extension_module' => array(),
    'detail_visited' => false,
    'data' => null,
    'app_master' => env('APP_MASTER', false),
    'installed' => env('APP_INSTALLED', 0),
    'public_path' => env('PUBLIC_PATH', null),
    'version' => null,
    'timezone' => env('APP_TIMEZONE','Asia/Jakarta'),
    'template' => env('TEMPLATE_PATH', null),
    'env_key'=>env('ENV_KEY',null),
    'custom_menu' => null,
    'custom_web_route'=>null,
    'sidebar'=>null
];
